### ISSUE TITLE
.htaccess fixes

### ISSUE THREAD

**Issue by thebrentc** [peacenews/ecosystem#7]
Suggested (tbc):

# lock down php processable files [?]
AddHandler php-script .php
# some server setups default to full <?php tags
php_value short_open_tag on
RewriteEngine on
#Prevent viewing of .sql setup files
RewriteRule ^.*.sql$ - [F,L,NC]

**Comment by cyborgasmic69** [comment]
The use of short php tags should be abandoned and certainly not enforced within .htaccess.

As per coding standards (see #8 ) the only suitable short-tag should be <?= $var ?> which is useable even if short-tag support is switched off.

**Comment by cyborgasmic69** [comment]
I've added a basic .htaccess file to the repo now (#13) which allows basic navigation. 

I think this issue can be closed now.

**Comment by thebrentc** [comment]
PHP tags issue fixed, thanks- I should have closed a while ago.
